const NATION_CODES = {
  Argentina: 'ARG',
  Portugal: 'POR',
  France: 'FRA',
  Brazil: 'BRA',
  Norway: 'NOR',
  Egypt: 'EGY',
  Belgium: 'BEL',
  Croatia: 'CRO',
  England: 'ENG',
  Scotland: 'SCO',
  Germany: 'GER',
  Spain: 'ESP',
  Netherlands: 'NED',
  Poland: 'POL',
  Slovenia: 'SVN',
  Italy: 'ITA',
  Uruguay: 'URU',
  Morocco: 'MAR',
  Sweden: 'SWE',
  Canada: 'CAN',
  Colombia: 'COL',
  Senegal: 'SEN',
  Cameroon: 'CMR',
  Algeria: 'ALG',
  Georgia: 'GEO',
  Hungary: 'HUN',
  Austria: 'AUT',
  Nigeria: 'NGA',
  Serbia: 'SRB',
  Denmark: 'DEN',
  Switzerland: 'SUI',
  'Ivory Coast': 'CIV',
  Jamaica: 'JAM',
  'New Zealand': 'NZL',
}

export function getNationCode(nationality) {
  return NATION_CODES[nationality] || nationality.slice(0, 3).toUpperCase()
}
